In [3]:
import numpy as np

In [4]:
np?

In [5]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([2.5,3,"s"])

array(['2.5', '3', 's'], dtype='<U32')

In [10]:
%%timeit
l1=list(range(5000000))
l2=list(range(5000000))


256 ms ± 5.87 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
%%timeit
np_array_1=np.arange(5000000)
np_array_2=np.arange(5000000)


19.6 ms ± 476 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [16]:
np.array([range(i,i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [18]:
from numpy import array
from numpy import mean
v=array([1,2,3,4,5,6])
print(v)
result=mean(v)
print(result)

[1 2 3 4 5 6]
3.5


In [19]:
from numpy import array
from numpy import var
v=array([1,2,3,4,5,6])
print(v)
result=var(v,ddof=1)
print(result)

[1 2 3 4 5 6]
3.5


In [22]:
from numpy import array
from numpy import cov
x=array([1,2,3,4,5,6,7,8,9])
print(x)
y=array([9,8,7,6,5,4,3,2,1])
print(y)
Sigma=cov(x,y)[0,1]
print(Sigma)


[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-7.5


# working with pandas package

In [25]:
import pandas as pd
s=pd.Series([1,2,3,np.nan,5,6],
index=['A','B','C','D','E','F'])
print(s)

A    1.0
B    2.0
C    3.0
D    NaN
E    5.0
F    6.0
dtype: float64


In [26]:
data={'Gender':['F','M','M'],'Emp_ID':['E01','E02','E03'],'Age':[25,27,25]}

In [27]:
df=pd.DataFrame(data,
columns=['Emp_ID','Gender','Age']               )

In [28]:
df

Emp_ID Gender  Age
0    E01      F   25
1    E02      M   27
2    E03      M   25